// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        (unknown)
// source: filters/v1alpha1/api_key_auth.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIKeyAuthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthServer *APIKeyAuthConfig_AuthServer `protobuf:"bytes,3,opt,name=auth_server,json=authServer,proto3" json:"auth_server,omitempty"`
}

func (x *APIKeyAuthConfig) Reset() {
	*x = APIKeyAuthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeyAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyAuthConfig) ProtoMessage() {}

func (x *APIKeyAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyAuthConfig.ProtoReflect.Descriptor instead.
func (*APIKeyAuthConfig) Descriptor() ([]byte, []int) {
	return file_filters_v1alpha1_api_key_auth_proto_rawDescGZIP(), []int{0}
}

func (x *APIKeyAuthConfig) GetAuthServer() *APIKeyAuthConfig_AuthServer {
	if x != nil {
		return x.AuthServer
	}
	return nil
}

type UsageStatsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatsServer *UsageStatsConfig_StatsServer `protobuf:"bytes,3,opt,name=stats_server,json=statsServer,proto3" json:"stats_server,omitempty"`
}

func (x *UsageStatsConfig) Reset() {
	*x = UsageStatsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageStatsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStatsConfig) ProtoMessage() {}

func (x *UsageStatsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStatsConfig.ProtoReflect.Descriptor instead.
func (*UsageStatsConfig) Descriptor() ([]byte, []int) {
	return file_filters_v1alpha1_api_key_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UsageStatsConfig) GetStatsServer() *UsageStatsConfig_StatsServer {
	if x != nil {
		return x.StatsServer
	}
	return nil
}

type OpenAIRequestHandlerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpenAIRequestHandlerConfig) Reset() {
	*x = OpenAIRequestHandlerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAIRequestHandlerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIRequestHandlerConfig) ProtoMessage() {}

func (x *OpenAIRequestHandlerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIRequestHandlerConfig.ProtoReflect.Descriptor instead.
func (*OpenAIRequestHandlerConfig) Descriptor() ([]byte, []int) {
	return file_filters_v1alpha1_api_key_auth_proto_rawDescGZIP(), []int{2}
}

type OpenAIResponseHandlerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpenAIResponseHandlerConfig) Reset() {
	*x = OpenAIResponseHandlerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAIResponseHandlerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIResponseHandlerConfig) ProtoMessage() {}

func (x *OpenAIResponseHandlerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIResponseHandlerConfig.ProtoReflect.Descriptor instead.
func (*OpenAIResponseHandlerConfig) Descriptor() ([]byte, []int) {
	return file_filters_v1alpha1_api_key_auth_proto_rawDescGZIP(), []int{3}
}

type APIKeyAuthConfig_AuthServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // Default is 3s
}

func (x *APIKeyAuthConfig_AuthServer) Reset() {
	*x = APIKeyAuthConfig_AuthServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeyAuthConfig_AuthServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyAuthConfig_AuthServer) ProtoMessage() {}

func (x *APIKeyAuthConfig_AuthServer) ProtoReflect() protoreflect.Message {
	mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyAuthConfig_AuthServer.ProtoReflect.Descriptor instead.
func (*APIKeyAuthConfig_AuthServer) Descriptor() ([]byte, []int) {
	return file_filters_v1alpha1_api_key_auth_proto_rawDescGZIP(), []int{0, 0}
}

func (x *APIKeyAuthConfig_AuthServer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *APIKeyAuthConfig_AuthServer) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type UsageStatsConfig_StatsServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // Default is 3s
}

func (x *UsageStatsConfig_StatsServer) Reset() {
	*x = UsageStatsConfig_StatsServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageStatsConfig_StatsServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStatsConfig_StatsServer) ProtoMessage() {}

func (x *UsageStatsConfig_StatsServer) ProtoReflect() protoreflect.Message {
	mi := &file_filters_v1alpha1_api_key_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStatsConfig_StatsServer.ProtoReflect.Descriptor instead.
func (*UsageStatsConfig_StatsServer) Descriptor() ([]byte, []int) {
	return file_filters_v1alpha1_api_key_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UsageStatsConfig_StatsServer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UsageStatsConfig_StatsServer) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_filters_v1alpha1_api_key_auth_proto protoreflect.FileDescriptor

var file_filters_v1alpha1_api_key_auth_proto_rawDesc = []byte{
	0x0a, 0x23, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6b, 0x6e, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe,
	0x01, 0x0a, 0x10, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x55, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x61,
	0x79, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x0a,
	0x61, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x53, 0x0a, 0x0a, 0x41, 0x75,
	0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x33, 0x0a, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22,
	0xc2, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x58, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6b, 0x6e, 0x6f,
	0x77, 0x61, 0x79, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x54,
	0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x33, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x49, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0x1d, 0x0a, 0x1b, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x49, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x42, 0x21, 0x5a, 0x1f, 0x6b, 0x6e, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filters_v1alpha1_api_key_auth_proto_rawDescOnce sync.Once
	file_filters_v1alpha1_api_key_auth_proto_rawDescData = file_filters_v1alpha1_api_key_auth_proto_rawDesc
)

func file_filters_v1alpha1_api_key_auth_proto_rawDescGZIP() []byte {
	file_filters_v1alpha1_api_key_auth_proto_rawDescOnce.Do(func() {
		file_filters_v1alpha1_api_key_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_filters_v1alpha1_api_key_auth_proto_rawDescData)
	})
	return file_filters_v1alpha1_api_key_auth_proto_rawDescData
}

var file_filters_v1alpha1_api_key_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_filters_v1alpha1_api_key_auth_proto_goTypes = []interface{}{
	(*APIKeyAuthConfig)(nil),             // 0: knoway.filters.v1alpha1.APIKeyAuthConfig
	(*UsageStatsConfig)(nil),             // 1: knoway.filters.v1alpha1.UsageStatsConfig
	(*OpenAIRequestHandlerConfig)(nil),   // 2: knoway.filters.v1alpha1.OpenAIRequestHandlerConfig
	(*OpenAIResponseHandlerConfig)(nil),  // 3: knoway.filters.v1alpha1.OpenAIResponseHandlerConfig
	(*APIKeyAuthConfig_AuthServer)(nil),  // 4: knoway.filters.v1alpha1.APIKeyAuthConfig.AuthServer
	(*UsageStatsConfig_StatsServer)(nil), // 5: knoway.filters.v1alpha1.UsageStatsConfig.StatsServer
	(*durationpb.Duration)(nil),          // 6: google.protobuf.Duration
}
var file_filters_v1alpha1_api_key_auth_proto_depIdxs = []int32{
	4, // 0: knoway.filters.v1alpha1.APIKeyAuthConfig.auth_server:type_name -> knoway.filters.v1alpha1.APIKeyAuthConfig.AuthServer
	5, // 1: knoway.filters.v1alpha1.UsageStatsConfig.stats_server:type_name -> knoway.filters.v1alpha1.UsageStatsConfig.StatsServer
	6, // 2: knoway.filters.v1alpha1.APIKeyAuthConfig.AuthServer.timeout:type_name -> google.protobuf.Duration
	6, // 3: knoway.filters.v1alpha1.UsageStatsConfig.StatsServer.timeout:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_filters_v1alpha1_api_key_auth_proto_init() }
func file_filters_v1alpha1_api_key_auth_proto_init() {
	if File_filters_v1alpha1_api_key_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filters_v1alpha1_api_key_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeyAuthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_v1alpha1_api_key_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsageStatsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_v1alpha1_api_key_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAIRequestHandlerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_v1alpha1_api_key_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAIResponseHandlerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_v1alpha1_api_key_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeyAuthConfig_AuthServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_v1alpha1_api_key_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsageStatsConfig_StatsServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filters_v1alpha1_api_key_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filters_v1alpha1_api_key_auth_proto_goTypes,
		DependencyIndexes: file_filters_v1alpha1_api_key_auth_proto_depIdxs,
		MessageInfos:      file_filters_v1alpha1_api_key_auth_proto_msgTypes,
	}.Build()
	File_filters_v1alpha1_api_key_auth_proto = out.File
	file_filters_v1alpha1_api_key_auth_proto_rawDesc = nil
	file_filters_v1alpha1_api_key_auth_proto_goTypes = nil
	file_filters_v1alpha1_api_key_auth_proto_depIdxs = nil
}
