// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: service/v1alpha1/apikey_auth.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIKeyAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *APIKeyAuthRequest) Reset() {
	*x = APIKeyAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1alpha1_apikey_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeyAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyAuthRequest) ProtoMessage() {}

func (x *APIKeyAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1alpha1_apikey_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyAuthRequest.ProtoReflect.Descriptor instead.
func (*APIKeyAuthRequest) Descriptor() ([]byte, []int) {
	return file_service_v1alpha1_apikey_auth_proto_rawDescGZIP(), []int{0}
}

func (x *APIKeyAuthRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type APIKeyAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// is_valid required: If it is true, it means that the apikey is valid.
	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	// allow_models optional: If it is empty, it means that the apikey can
	// access all models. If it is not empty, it means that the apikey can only
	// access the specified models.
	// The matching rules for each value follow the rules of glob.
	AllowModels []string `protobuf:"bytes,2,rep,name=allow_models,json=allowModels,proto3" json:"allow_models,omitempty"`
	// api_key_id optional: It will be used in statistics to avoid leakage of
	// sensitive information.
	ApiKeyId string `protobuf:"bytes,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	// user_id optional: the apikey's owner, will be used in route matching.
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// deny_models optional: similar to allow_models, but the opposite.
	// If it is not empty, it means that the apikey
	// cannot access the specified models.
	// The matching rules for each value follow the rules of glob.
	// it has higher priority than allow_models.
	DenyModels []string `protobuf:"bytes,5,rep,name=deny_models,json=denyModels,proto3" json:"deny_models,omitempty"`
}

func (x *APIKeyAuthResponse) Reset() {
	*x = APIKeyAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1alpha1_apikey_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeyAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyAuthResponse) ProtoMessage() {}

func (x *APIKeyAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1alpha1_apikey_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyAuthResponse.ProtoReflect.Descriptor instead.
func (*APIKeyAuthResponse) Descriptor() ([]byte, []int) {
	return file_service_v1alpha1_apikey_auth_proto_rawDescGZIP(), []int{1}
}

func (x *APIKeyAuthResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *APIKeyAuthResponse) GetAllowModels() []string {
	if x != nil {
		return x.AllowModels
	}
	return nil
}

func (x *APIKeyAuthResponse) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *APIKeyAuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIKeyAuthResponse) GetDenyModels() []string {
	if x != nil {
		return x.DenyModels
	}
	return nil
}

var File_service_v1alpha1_apikey_auth_proto protoreflect.FileDescriptor

var file_service_v1alpha1_apikey_auth_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6b, 0x6e, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x2c, 0x0a,
	0x11, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x22, 0xaa, 0x01, 0x0a, 0x12,
	0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x12, 0x1c, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x6e, 0x79, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65,
	0x6e, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x32, 0x76, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x0a, 0x41, 0x50, 0x49, 0x4b, 0x65,
	0x79, 0x41, 0x75, 0x74, 0x68, 0x12, 0x2a, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x50, 0x49, 0x4b,
	0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x21, 0x5a, 0x1f, 0x6b, 0x6e, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_v1alpha1_apikey_auth_proto_rawDescOnce sync.Once
	file_service_v1alpha1_apikey_auth_proto_rawDescData = file_service_v1alpha1_apikey_auth_proto_rawDesc
)

func file_service_v1alpha1_apikey_auth_proto_rawDescGZIP() []byte {
	file_service_v1alpha1_apikey_auth_proto_rawDescOnce.Do(func() {
		file_service_v1alpha1_apikey_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_v1alpha1_apikey_auth_proto_rawDescData)
	})
	return file_service_v1alpha1_apikey_auth_proto_rawDescData
}

var file_service_v1alpha1_apikey_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_v1alpha1_apikey_auth_proto_goTypes = []interface{}{
	(*APIKeyAuthRequest)(nil),  // 0: knoway.service.v1alpha1.APIKeyAuthRequest
	(*APIKeyAuthResponse)(nil), // 1: knoway.service.v1alpha1.APIKeyAuthResponse
}
var file_service_v1alpha1_apikey_auth_proto_depIdxs = []int32{
	0, // 0: knoway.service.v1alpha1.AuthService.APIKeyAuth:input_type -> knoway.service.v1alpha1.APIKeyAuthRequest
	1, // 1: knoway.service.v1alpha1.AuthService.APIKeyAuth:output_type -> knoway.service.v1alpha1.APIKeyAuthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_v1alpha1_apikey_auth_proto_init() }
func file_service_v1alpha1_apikey_auth_proto_init() {
	if File_service_v1alpha1_apikey_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_v1alpha1_apikey_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeyAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1alpha1_apikey_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeyAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_v1alpha1_apikey_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1alpha1_apikey_auth_proto_goTypes,
		DependencyIndexes: file_service_v1alpha1_apikey_auth_proto_depIdxs,
		MessageInfos:      file_service_v1alpha1_apikey_auth_proto_msgTypes,
	}.Build()
	File_service_v1alpha1_apikey_auth_proto = out.File
	file_service_v1alpha1_apikey_auth_proto_rawDesc = nil
	file_service_v1alpha1_apikey_auth_proto_goTypes = nil
	file_service_v1alpha1_apikey_auth_proto_depIdxs = nil
}
