// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: admin/v1alpha1/config_dump.proto

package v1alpha1

import (
	_ "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigDump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listeners []*anypb.Any `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	Clusters  []*anypb.Any `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Routes    []*anypb.Any `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *ConfigDump) Reset() {
	*x = ConfigDump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_v1alpha1_config_dump_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDump) ProtoMessage() {}

func (x *ConfigDump) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1alpha1_config_dump_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDump.ProtoReflect.Descriptor instead.
func (*ConfigDump) Descriptor() ([]byte, []int) {
	return file_admin_v1alpha1_config_dump_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigDump) GetListeners() []*anypb.Any {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *ConfigDump) GetClusters() []*anypb.Any {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ConfigDump) GetRoutes() []*anypb.Any {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_admin_v1alpha1_config_dump_proto protoreflect.FileDescriptor

var file_admin_v1alpha1_config_dump_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x6b, 0x6e, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44,
	0x75, 0x6d, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x09, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x42, 0x1f, 0x5a, 0x1d, 0x6b, 0x6e, 0x6f, 0x77, 0x61,
	0x79, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_v1alpha1_config_dump_proto_rawDescOnce sync.Once
	file_admin_v1alpha1_config_dump_proto_rawDescData = file_admin_v1alpha1_config_dump_proto_rawDesc
)

func file_admin_v1alpha1_config_dump_proto_rawDescGZIP() []byte {
	file_admin_v1alpha1_config_dump_proto_rawDescOnce.Do(func() {
		file_admin_v1alpha1_config_dump_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_v1alpha1_config_dump_proto_rawDescData)
	})
	return file_admin_v1alpha1_config_dump_proto_rawDescData
}

var file_admin_v1alpha1_config_dump_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_admin_v1alpha1_config_dump_proto_goTypes = []interface{}{
	(*ConfigDump)(nil), // 0: knoway.admin.v1alpha1.ConfigDump
	(*anypb.Any)(nil),  // 1: google.protobuf.Any
}
var file_admin_v1alpha1_config_dump_proto_depIdxs = []int32{
	1, // 0: knoway.admin.v1alpha1.ConfigDump.listeners:type_name -> google.protobuf.Any
	1, // 1: knoway.admin.v1alpha1.ConfigDump.clusters:type_name -> google.protobuf.Any
	1, // 2: knoway.admin.v1alpha1.ConfigDump.routes:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_admin_v1alpha1_config_dump_proto_init() }
func file_admin_v1alpha1_config_dump_proto_init() {
	if File_admin_v1alpha1_config_dump_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_v1alpha1_config_dump_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigDump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_v1alpha1_config_dump_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1alpha1_config_dump_proto_goTypes,
		DependencyIndexes: file_admin_v1alpha1_config_dump_proto_depIdxs,
		MessageInfos:      file_admin_v1alpha1_config_dump_proto_msgTypes,
	}.Build()
	File_admin_v1alpha1_config_dump_proto = out.File
	file_admin_v1alpha1_config_dump_proto_rawDesc = nil
	file_admin_v1alpha1_config_dump_proto_goTypes = nil
	file_admin_v1alpha1_config_dump_proto_depIdxs = nil
}
