//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendUpstream) DeepCopyInto(out *BackendUpstream) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		copy(*out, *in)
	}
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]HeaderFromSource, len(*in))
		copy(*out, *in)
	}
	if in.DefaultParams != nil {
		in, out := &in.DefaultParams, &out.DefaultParams
		*out = new(ModelParams)
		(*in).DeepCopyInto(*out)
	}
	if in.OverrideParams != nil {
		in, out := &in.OverrideParams, &out.OverrideParams
		*out = new(ModelParams)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveParamKeys != nil {
		in, out := &in.RemoveParamKeys, &out.RemoveParamKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendUpstream.
func (in *BackendUpstream) DeepCopy() *BackendUpstream {
	if in == nil {
		return nil
	}
	out := new(BackendUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonParams) DeepCopyInto(out *CommonParams) {
	*out = *in
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonParams.
func (in *CommonParams) DeepCopy() *CommonParams {
	if in == nil {
		return nil
	}
	out := new(CommonParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterConfig) DeepCopyInto(out *FilterConfig) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterConfig.
func (in *FilterConfig) DeepCopy() *FilterConfig {
	if in == nil {
		return nil
	}
	out := new(FilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Header) DeepCopyInto(out *Header) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Header.
func (in *Header) DeepCopy() *Header {
	if in == nil {
		return nil
	}
	out := new(Header)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderFromSource) DeepCopyInto(out *HeaderFromSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderFromSource.
func (in *HeaderFromSource) DeepCopy() *HeaderFromSource {
	if in == nil {
		return nil
	}
	out := new(HeaderFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationBackend) DeepCopyInto(out *ImageGenerationBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationBackend.
func (in *ImageGenerationBackend) DeepCopy() *ImageGenerationBackend {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageGenerationBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationBackendList) DeepCopyInto(out *ImageGenerationBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImageGenerationBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationBackendList.
func (in *ImageGenerationBackendList) DeepCopy() *ImageGenerationBackendList {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageGenerationBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationBackendSpec) DeepCopyInto(out *ImageGenerationBackendSpec) {
	*out = *in
	if in.ModelName != nil {
		in, out := &in.ModelName, &out.ModelName
		*out = new(string)
		**out = **in
	}
	in.Upstream.DeepCopyInto(&out.Upstream)
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]ImageGenerationFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MeteringPolicy != nil {
		in, out := &in.MeteringPolicy, &out.MeteringPolicy
		*out = new(ImageGenerationMeteringPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationBackendSpec.
func (in *ImageGenerationBackendSpec) DeepCopy() *ImageGenerationBackendSpec {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationBackendStatus) DeepCopyInto(out *ImageGenerationBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationBackendStatus.
func (in *ImageGenerationBackendStatus) DeepCopy() *ImageGenerationBackendStatus {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationBackendUpstream) DeepCopyInto(out *ImageGenerationBackendUpstream) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		copy(*out, *in)
	}
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]HeaderFromSource, len(*in))
		copy(*out, *in)
	}
	if in.DefaultParams != nil {
		in, out := &in.DefaultParams, &out.DefaultParams
		*out = new(ImageGenerationModelParams)
		(*in).DeepCopyInto(*out)
	}
	if in.OverrideParams != nil {
		in, out := &in.OverrideParams, &out.OverrideParams
		*out = new(ImageGenerationModelParams)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveParamKeys != nil {
		in, out := &in.RemoveParamKeys, &out.RemoveParamKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationBackendUpstream.
func (in *ImageGenerationBackendUpstream) DeepCopy() *ImageGenerationBackendUpstream {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationBackendUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationCommonParams) DeepCopyInto(out *ImageGenerationCommonParams) {
	*out = *in
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationCommonParams.
func (in *ImageGenerationCommonParams) DeepCopy() *ImageGenerationCommonParams {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationCommonParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationFilter) DeepCopyInto(out *ImageGenerationFilter) {
	*out = *in
	in.ImageGenerationFilterFilterConfig.DeepCopyInto(&out.ImageGenerationFilterFilterConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationFilter.
func (in *ImageGenerationFilter) DeepCopy() *ImageGenerationFilter {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationFilterFilterConfig) DeepCopyInto(out *ImageGenerationFilterFilterConfig) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationFilterFilterConfig.
func (in *ImageGenerationFilterFilterConfig) DeepCopy() *ImageGenerationFilterFilterConfig {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationFilterFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationMeteringPolicy) DeepCopyInto(out *ImageGenerationMeteringPolicy) {
	*out = *in
	if in.SizeFrom != nil {
		in, out := &in.SizeFrom, &out.SizeFrom
		*out = new(SizeFrom)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationMeteringPolicy.
func (in *ImageGenerationMeteringPolicy) DeepCopy() *ImageGenerationMeteringPolicy {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationMeteringPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageGenerationModelParams) DeepCopyInto(out *ImageGenerationModelParams) {
	*out = *in
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAIImageGenerationParam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageGenerationModelParams.
func (in *ImageGenerationModelParams) DeepCopy() *ImageGenerationModelParams {
	if in == nil {
		return nil
	}
	out := new(ImageGenerationModelParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackend) DeepCopyInto(out *LLMBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackend.
func (in *LLMBackend) DeepCopy() *LLMBackend {
	if in == nil {
		return nil
	}
	out := new(LLMBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackendFilter) DeepCopyInto(out *LLMBackendFilter) {
	*out = *in
	in.FilterConfig.DeepCopyInto(&out.FilterConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendFilter.
func (in *LLMBackendFilter) DeepCopy() *LLMBackendFilter {
	if in == nil {
		return nil
	}
	out := new(LLMBackendFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackendList) DeepCopyInto(out *LLMBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendList.
func (in *LLMBackendList) DeepCopy() *LLMBackendList {
	if in == nil {
		return nil
	}
	out := new(LLMBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackendSpec) DeepCopyInto(out *LLMBackendSpec) {
	*out = *in
	if in.ModelName != nil {
		in, out := &in.ModelName, &out.ModelName
		*out = new(string)
		**out = **in
	}
	in.Upstream.DeepCopyInto(&out.Upstream)
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]LLMBackendFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendSpec.
func (in *LLMBackendSpec) DeepCopy() *LLMBackendSpec {
	if in == nil {
		return nil
	}
	out := new(LLMBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackendStatus) DeepCopyInto(out *LLMBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendStatus.
func (in *LLMBackendStatus) DeepCopy() *LLMBackendStatus {
	if in == nil {
		return nil
	}
	out := new(LLMBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelParams) DeepCopyInto(out *ModelParams) {
	*out = *in
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAIParam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelParams.
func (in *ModelParams) DeepCopy() *ModelParams {
	if in == nil {
		return nil
	}
	out := new(ModelParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRoute) DeepCopyInto(out *ModelRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRoute.
func (in *ModelRoute) DeepCopy() *ModelRoute {
	if in == nil {
		return nil
	}
	out := new(ModelRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteFallback) DeepCopyInto(out *ModelRouteFallback) {
	*out = *in
	if in.PreDelay != nil {
		in, out := &in.PreDelay, &out.PreDelay
		*out = new(int64)
		**out = **in
	}
	if in.PostDelay != nil {
		in, out := &in.PostDelay, &out.PostDelay
		*out = new(int64)
		**out = **in
	}
	if in.MaxRetires != nil {
		in, out := &in.MaxRetires, &out.MaxRetires
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteFallback.
func (in *ModelRouteFallback) DeepCopy() *ModelRouteFallback {
	if in == nil {
		return nil
	}
	out := new(ModelRouteFallback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteFilter) DeepCopyInto(out *ModelRouteFilter) {
	*out = *in
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteFilter.
func (in *ModelRouteFilter) DeepCopy() *ModelRouteFilter {
	if in == nil {
		return nil
	}
	out := new(ModelRouteFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteList) DeepCopyInto(out *ModelRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteList.
func (in *ModelRouteList) DeepCopy() *ModelRouteList {
	if in == nil {
		return nil
	}
	out := new(ModelRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteRoute) DeepCopyInto(out *ModelRouteRoute) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ModelRouteRouteTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteRoute.
func (in *ModelRouteRoute) DeepCopy() *ModelRouteRoute {
	if in == nil {
		return nil
	}
	out := new(ModelRouteRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteRouteFallback) DeepCopyInto(out *ModelRouteRouteFallback) {
	*out = *in
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteRouteFallback.
func (in *ModelRouteRouteFallback) DeepCopy() *ModelRouteRouteFallback {
	if in == nil {
		return nil
	}
	out := new(ModelRouteRouteFallback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteRouteTarget) DeepCopyInto(out *ModelRouteRouteTarget) {
	*out = *in
	in.Destination.DeepCopyInto(&out.Destination)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteRouteTarget.
func (in *ModelRouteRouteTarget) DeepCopy() *ModelRouteRouteTarget {
	if in == nil {
		return nil
	}
	out := new(ModelRouteRouteTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteRouteTargetDestination) DeepCopyInto(out *ModelRouteRouteTargetDestination) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteRouteTargetDestination.
func (in *ModelRouteRouteTargetDestination) DeepCopy() *ModelRouteRouteTargetDestination {
	if in == nil {
		return nil
	}
	out := new(ModelRouteRouteTargetDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteSpec) DeepCopyInto(out *ModelRouteSpec) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]ModelRouteFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(ModelRouteRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(ModelRouteFallback)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteSpec.
func (in *ModelRouteSpec) DeepCopy() *ModelRouteSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteStatus) DeepCopyInto(out *ModelRouteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ModelRouteStatusTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteStatus.
func (in *ModelRouteStatus) DeepCopy() *ModelRouteStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouteStatusTarget) DeepCopyInto(out *ModelRouteStatusTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouteStatusTarget.
func (in *ModelRouteStatusTarget) DeepCopy() *ModelRouteStatusTarget {
	if in == nil {
		return nil
	}
	out := new(ModelRouteStatusTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIImageGenerationParam) DeepCopyInto(out *OpenAIImageGenerationParam) {
	*out = *in
	in.ImageGenerationCommonParams.DeepCopyInto(&out.ImageGenerationCommonParams)
	if in.N != nil {
		in, out := &in.N, &out.N
		*out = new(string)
		**out = **in
	}
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(string)
		**out = **in
	}
	if in.ResponseFormat != nil {
		in, out := &in.ResponseFormat, &out.ResponseFormat
		*out = new(OpenAIImageGenerationResponseFormat)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.Style != nil {
		in, out := &in.Style, &out.Style
		*out = new(OpenAIImageGenerationStyle)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
	if in.NegativePrompt != nil {
		in, out := &in.NegativePrompt, &out.NegativePrompt
		*out = new(string)
		**out = **in
	}
	if in.GuidanceScale != nil {
		in, out := &in.GuidanceScale, &out.GuidanceScale
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIImageGenerationParam.
func (in *OpenAIImageGenerationParam) DeepCopy() *OpenAIImageGenerationParam {
	if in == nil {
		return nil
	}
	out := new(OpenAIImageGenerationParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIModelNameRewriteConfig) DeepCopyInto(out *OpenAIModelNameRewriteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIModelNameRewriteConfig.
func (in *OpenAIModelNameRewriteConfig) DeepCopy() *OpenAIModelNameRewriteConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIModelNameRewriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIParam) DeepCopyInto(out *OpenAIParam) {
	*out = *in
	in.CommonParams.DeepCopyInto(&out.CommonParams)
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int)
		**out = **in
	}
	if in.MaxCompletionTokens != nil {
		in, out := &in.MaxCompletionTokens, &out.MaxCompletionTokens
		*out = new(int)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(string)
		**out = **in
	}
	if in.Stream != nil {
		in, out := &in.Stream, &out.Stream
		*out = new(bool)
		**out = **in
	}
	if in.StreamOptions != nil {
		in, out := &in.StreamOptions, &out.StreamOptions
		*out = new(StreamOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIParam.
func (in *OpenAIParam) DeepCopy() *OpenAIParam {
	if in == nil {
		return nil
	}
	out := new(OpenAIParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAITextToSpeechParam) DeepCopyInto(out *OpenAITextToSpeechParam) {
	*out = *in
	in.TextToSpeechCommonParams.DeepCopyInto(&out.TextToSpeechCommonParams)
	if in.ResponseFormat != nil {
		in, out := &in.ResponseFormat, &out.ResponseFormat
		*out = new(OpenAITextToSpeechResponseFormat)
		**out = **in
	}
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAITextToSpeechParam.
func (in *OpenAITextToSpeechParam) DeepCopy() *OpenAITextToSpeechParam {
	if in == nil {
		return nil
	}
	out := new(OpenAITextToSpeechParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitPolicy) DeepCopyInto(out *RateLimitPolicy) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]*RateLimitRule, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RateLimitRule)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicy.
func (in *RateLimitPolicy) DeepCopy() *RateLimitPolicy {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitRule) DeepCopyInto(out *RateLimitRule) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(StringMatch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitRule.
func (in *RateLimitRule) DeepCopy() *RateLimitRule {
	if in == nil {
		return nil
	}
	out := new(RateLimitRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamOptions) DeepCopyInto(out *StreamOptions) {
	*out = *in
	if in.IncludeUsage != nil {
		in, out := &in.IncludeUsage, &out.IncludeUsage
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamOptions.
func (in *StreamOptions) DeepCopy() *StreamOptions {
	if in == nil {
		return nil
	}
	out := new(StreamOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch) DeepCopyInto(out *StringMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch.
func (in *StringMatch) DeepCopy() *StringMatch {
	if in == nil {
		return nil
	}
	out := new(StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechBackend) DeepCopyInto(out *TextToSpeechBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechBackend.
func (in *TextToSpeechBackend) DeepCopy() *TextToSpeechBackend {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TextToSpeechBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechBackendList) DeepCopyInto(out *TextToSpeechBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TextToSpeechBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechBackendList.
func (in *TextToSpeechBackendList) DeepCopy() *TextToSpeechBackendList {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TextToSpeechBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechBackendSpec) DeepCopyInto(out *TextToSpeechBackendSpec) {
	*out = *in
	if in.ModelName != nil {
		in, out := &in.ModelName, &out.ModelName
		*out = new(string)
		**out = **in
	}
	in.Upstream.DeepCopyInto(&out.Upstream)
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]TextToSpeechFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechBackendSpec.
func (in *TextToSpeechBackendSpec) DeepCopy() *TextToSpeechBackendSpec {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechBackendStatus) DeepCopyInto(out *TextToSpeechBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechBackendStatus.
func (in *TextToSpeechBackendStatus) DeepCopy() *TextToSpeechBackendStatus {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechBackendUpstream) DeepCopyInto(out *TextToSpeechBackendUpstream) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		copy(*out, *in)
	}
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]HeaderFromSource, len(*in))
		copy(*out, *in)
	}
	if in.DefaultParams != nil {
		in, out := &in.DefaultParams, &out.DefaultParams
		*out = new(TextToSpeechModelParams)
		(*in).DeepCopyInto(*out)
	}
	if in.OverrideParams != nil {
		in, out := &in.OverrideParams, &out.OverrideParams
		*out = new(TextToSpeechModelParams)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveParamKeys != nil {
		in, out := &in.RemoveParamKeys, &out.RemoveParamKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechBackendUpstream.
func (in *TextToSpeechBackendUpstream) DeepCopy() *TextToSpeechBackendUpstream {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechBackendUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechCommonParams) DeepCopyInto(out *TextToSpeechCommonParams) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(string)
		**out = **in
	}
	if in.Voice != nil {
		in, out := &in.Voice, &out.Voice
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechCommonParams.
func (in *TextToSpeechCommonParams) DeepCopy() *TextToSpeechCommonParams {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechCommonParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechFilter) DeepCopyInto(out *TextToSpeechFilter) {
	*out = *in
	in.TextToSpeechFilterConfig.DeepCopyInto(&out.TextToSpeechFilterConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechFilter.
func (in *TextToSpeechFilter) DeepCopy() *TextToSpeechFilter {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechFilterConfig) DeepCopyInto(out *TextToSpeechFilterConfig) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechFilterConfig.
func (in *TextToSpeechFilterConfig) DeepCopy() *TextToSpeechFilterConfig {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextToSpeechModelParams) DeepCopyInto(out *TextToSpeechModelParams) {
	*out = *in
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAITextToSpeechParam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextToSpeechModelParams.
func (in *TextToSpeechModelParams) DeepCopy() *TextToSpeechModelParams {
	if in == nil {
		return nil
	}
	out := new(TextToSpeechModelParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageStatsConfig) DeepCopyInto(out *UsageStatsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatsConfig.
func (in *UsageStatsConfig) DeepCopy() *UsageStatsConfig {
	if in == nil {
		return nil
	}
	out := new(UsageStatsConfig)
	in.DeepCopyInto(out)
	return out
}
